export const APP_BAR_HEIGHT = 60;

export const BOTTOM_BAR_HEIGHT = 64;

export const SIDEBAR_WIDTH = 320;

export const SIDEBAR_WIDTH_MOBILE = 240;

export const NOTIFICATION_BAR_BOTTOM_MARGIN = BOTTOM_BAR_HEIGHT + 66;
