"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/navigation/SideBar";
import NavBar from "@/components/navigation/NavBar";
import Footer from "@/components/footer/Footer";
import { DocsProvider } from "@/context/DocsContext";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DocsProvider>
          <NavBar />
          <div className="flex">
            <SideBar className="max-md:hidden" />
            {children}
          </div>

          <Footer />
        </DocsProvider>
      </body>
    </html>
  );
}
